apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-logs-pvc
  namespace: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: fastapi-logs-pv
