apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-logs-pv
  namespace: standard
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/fastapi-logs
  persistentVolumeReclaimPolicy: Retain
