
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-pv
  # Remove or comment out storageClassName
  # storageClassName: ""

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-data
#   namespace: standard
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: postgres-pv
